#!/bin/bash


infile="$1"

of_scrn="${2}"
of_dir="$(dirname -- "${of_scrn}")"
of_base="$(basename -- "${of_scrn%.*}")"
of_gfx="${of_dir}/${of_base}.2bpp"
of_map="${of_dir}/${of_base}.tilemap"


rgbgfx -o "${of_gfx}" -t "${of_map}" -d 2 -u -b 128 "${1}"

if [ -f "$of_scrn" ]; then
	mv "$of_scrn" "$of_scrn~"
fi


w() {
	echo "$@" >> "$of_scrn"
}

w "; this file generated by scrn.sh"
w "; at: $(date --iso-8601=seconds)"
w "; infile: '$1'"
w "; outfile '$2'"
w

w "${of_base}_tiles:"
w "	incbin \"${of_gfx}\""
w ".end"
w

w "${of_base}_map:"
w "	incbin \"${of_map}\""
w ".end"
w

w "${of_base}_tiles_size equ ${of_base}_tiles.end - ${of_base}_tiles"
w
